###
GET http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWIiLCJleHAiOjE3MzE0NDY2ODcsImlhdCI6MTczMTQxMDY4N30.rRSMWpZz5JwWGjgZQ9eyHoKGUWJRkW8BYI6b6jcicpw
Content-Type: application/json

<> 2024-11-12T123450.200.json

###
POST http://localhost:8080/api/product/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWIiLCJleHAiOjE3MzE0NDY2ODcsImlhdCI6MTczMTQxMDY4N30.rRSMWpZz5JwWGjgZQ9eyHoKGUWJRkW8BYI6b6jcicpw
Content-Type: application/json

{
  "name": "test",
  "description": "test20",
  "price": 9.99,
  "quantity": 10
}

<> 2024-11-12T123611.200.json

###
GET http://localhost:8080/api/product/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWIiLCJleHAiOjE3MzE0NDY2ODcsImlhdCI6MTczMTQxMDY4N30.rRSMWpZz5JwWGjgZQ9eyHoKGUWJRkW8BYI6b6jcicpw
Content-Type: application/json

<> 2024-11-12T123650.200.json

###
PATCH http://localhost:8080/api/product/2/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWIiLCJleHAiOjE3MzE0NDY2ODcsImlhdCI6MTczMTQxMDY4N30.rRSMWpZz5JwWGjgZQ9eyHoKGUWJRkW8BYI6b6jcicpw
Content-Type: application/json

{
  "name": "test update",
  "description": "test20 update",
  "price": 9.99,
  "quantity": 10
}

<> 2024-11-12T123800.200.json

###
DELETE http://localhost:8080/api/product/3/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWIiLCJleHAiOjE3MzE0NDY2ODcsImlhdCI6MTczMTQxMDY4N30.rRSMWpZz5JwWGjgZQ9eyHoKGUWJRkW8BYI6b6jcicpw

<> 2024-11-12T123843.200.txt

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "seb",
  "password": "1234"
}

<> 2024-11-12T124103.200.txt

###
POST http://localhost:8080/api/authenticate
Content-Type: application/json

{
  "username": "seb",
  "password": "1234"
}

<> 2024-11-12T124132.200.txt